#pragma once
#define WEZEL_XML_ROOT "Space-Explorers"
#define WEZEL_XML_LICZNIK "Licznik"
#define WEZEL_XML_BUDYNEK "Budynek"
#define WEZEL_XML_LADOWNIA "Ladownia"
#define WEZEL_XML_STATEK "Statek"
#define WEZEL_XML_FLOTA "Flota"
#define WEZEL_XML_GRA "Gra"
#define WEZEL_XML_UZYTKOWNIK "Uzytkownik"
#define WEZEL_XML_PLANETA "Planeta"
#define WEZEL_XML_OBIEKTY "Obiekty"
#define WEZEL_XML_FLOTY "Floty"
#define WEZEL_XML_SUROWCE "Surowce"
#define WEZEL_XML_TECHNOLOGIA "Technologia"

#define ATRYBUT_XML_IDENTYFIKATOR "id"
#define ATRYBUT_XML_POZIOM "poziom"
#define ATRYBUT_XML_IDENTYFIKATOR_PLANETY "idPlanety"
#define ATRYBUT_XML_ILOSC "ilosc"
#define ATRYBUT_XML_ZAJETE_MIEJSCE "zajeteMiejsce"