#pragma once

#include "Bool.h"
#include "Dystans.h"
#include "Fluktuacja.h"
#include "IdType.h"
#include "Ilosc.h"
#include "Klucz.h"
#include "Mapa.h"
#include "Masa.h"
#include "MocSilnika.h"
#include "Objetosc.h"
#include "Obrazenia.h"
#include "Parametr.h"
#include "Powierzchnia.h"
#include "Poziom.h"
#include "Predkosc.h"
#include "Tekst.h"
#include "ZuzyciePaliwa.h"

#include "Base.h"
