#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <sstream>
#include <stack>
#include <fstream>
#include <time.h>
#include <iostream>
#include <chrono>
#include <iomanip>