#define XML_WEZEL_ZMIANA "Zmiana"
#define XML_WEZEL_ZMIANA_PARAM "Param"

#define XML_ATRYBUT_ZMIANA_FOR "for"
#define XML_ATRYBUT_ZMIANA_ID "id"
#define XML_ATRYBUT_ZMIANA_WSPOLCZYNNIK "wspolczynnik"

#define XML_WARTOSC_ATRYBUTU_ZMIANA_BRAT "brat"
#define XML_WARTOSC_ATRYBUTU_ZMIANA_NASTEPNY "nastepny"
#define XML_WARTOSC_ATRYBUTU_ZMIANA_1 "1"
#define XML_WARTOSC_ATRYBUTU_ZMIANA_2 "2"
