#pragma once

#define RETURN_CODE_OK 0
#define RETURN_CODE_SERWER_JUZ_JEST_WLACZONY 1
#define RETURN_CODE_NIEODPOWIEDNI_TRYB_APLIKACJI 2

#define RETURN_CODE_SERWER_JUZ_JEST_WYLACZONY 3

#define RETURN_CODE_ISTNIEJE_POLACZENIE 4
#define RETURN_CODE_BRAK_POLACZENIA 5

