#define PLUGIN_BRAK_PLIKOW_ZMIAN "Brak plików *.dll w folderze pluginów!"
#define PLUGIN_ZALADOWANO_ZMIANE "Za³adowano biblioteke:"
#define PLUGIN_BLAD_LADOWANIA_ZMIANY "B³¹d ³adowania bilbioteki:"
#define PLUGIN_NIE_ZNALEZIONO_ZMIANY "Nie zanaleziono funkcji RejestrujZmiane."
#define PLUGIN_NIE_ZALADOWANO_ZMIANY "Nie za³adowano biblioteki:"
#define PLUGIN_NIE_ZAREJESTROWANO_ZMIANY "Nie zarejestrowano zmiany:"

#define PLUGIN_FOLDER_X86 "zmiana\\"
#define PLUGIN_FOLDER_X64 "zmiana-x64\\"
#define PLUGIN_PLIK_DEBUG "*-d.dll"
#define PLUGIN_PLIK_RELEASE "*-r.dll"