#pragma once
#define METODA_RPC_AUTORYZACJA "autoryzacja"
#define METODA_RPC_INSTANCJA "instancja"
#define METODA_RPC_METODA "metoda"
#define METODA_RPC_NAZWA "nazwa"
#define METODA_RPC_CRC "crc"
#define METODA_RPC_ID_UNIKALNE "id-unikalne"
#define METODA_RPC_POWTORZENIE "powtorzenie"
#define METODA_RPC_CZAS_WYWOLANIA "czas-wywolania"
#define METODA_RPC_CZAS_ODPOWIEDZI "czas-odpowiedzi"
#define METODA_RPC_PARAMETRY "parametry"
#define METODA_RPC_RETURN "return"

#define METODA_RPC_ERROR "error"
#define METODA_RPC_TYPE "typ"
#define METODA_RPC_EXCEPTION_TYPE "throw"
#define METODA_RPC_KOMUNIKAT "komunikat"
#define METODA_RPC_NUMER "numer"

#define TYPE_RPC_E_ERROR 1
#define TYPE_RPC_E_EXCEPTION 2
#define TYPE_RPC_E_SPECIALIZED_BY_METHOD 3

#define RPC_FLAG_COMPRESSION 0x1
#define RPC_FLAG_AUTHORIZATION 0x2

#define RPC_OK 0
#define RPC_ERROR_MISSING_AUTORYZACJA -1
#define RPC_ERROR_MISSING_INSTANCJA -2
#define RPC_ERROR_MISSING_METODA -3
#define RPC_ERROR_MISSING_NAZWA_METODY -4
#define RPC_ERROR_MISSING_ID_UNIKALNE -5
#define RPC_ERROR_MISSING_POWTORZENIE -6
#define RPC_ERROR_MISSING_CZAS_WYWOLANIA -7

#define RPC_ERROR_UNAUTHORIZED -8
#define RPC_ERROR_WITHOUT_AUTHORIZED -9
#define RPC_ERROR_NEED_AUTHORIZATION -10

#define RPC_ERROR_MISSING_CRC -11
#define RPC_ERROR_INVALID_CRC -12

#define RPC_ERROR_PREPROCESSING_FAIL -13
#define RPC_ERROR_SENDING_FAIL -14
#define RPC_ERROR_PARSING_FAIL -15
#define RPC_ERROR_MISSING_CZAS_ODPOWIEDZI -16
#define RPC_ERROR_INVALID_THROW_OBJECT -17
#define RPC_ERROR_METHOD_THROW -18
#define RPC_ERROR_RESPONSE_SERVICE_FAIL -19
#define RPC_ERROR_MISSING_RETURN -20

#define SOCK_CONNECTION_CLOSED -21

#define RPC_ERROR_NO_DATA -22
#define RPC_ERROR_COMPRESION_Z_MEM_ERROR -23
#define RPC_ERROR_COMPRESION_Z_BUF_ERROR -24
#define RPC_ERROR_COMPRESION_Z_DATA_ERROR -25
#define RPC_ERROR_UNIDENTIFYING -26
#define RPC_ERROR_DECRYPTION_FAIL -27
#define RPC_ERROR_MISSING_METHOD -28
#define RPC_ERROR_PROCESSING_METHOD -29
#define RPC_ERROR_EXCEPTION -30

#define SOCK_PROCCESSING_BREAK -31